const images = {
    tuvsalbar: require('../images/tuvsalbar.png'),
    emart: require('../images/emart.png'),
    zaisan: require('../images/зайсан.png'),
    unur: require('../images/unur.png'),
    sumber: require('../images/sumber ord.png'),
    house: require('../images/house.png'),
    foodcity: require('../images/food city.png'),
    efes: require('../images/efes.png'),
    cinema: require('../images/cinemanext.png'),
    moriton: require('../images/moriton.png'),
    sodon: require('../images/sodon.png'),
    start: require('../images/stars.png'),
    bumbugur: require('../images/bumbugur.png'),
    arvaiheer: require('../images/uvurkhangai.jpg'),
    sansar: require('../images/sansar.png'),
    parkod: require('../images/park od2.png'),
    erdenet: require('../images/erdenet.png'),
    darhan: require('../images/darhan.png'),
    minijurur: require('../images/minijurur.png'),
    locationlogo: require('../images/locationlogo.png'),
    mail: require('../images/mail.png'),
    dial: require('../images/dial.png'),
    worki: require('../images/worki.png'),
    zangia: require('../images/zangia.png'),
    hrbanner: require('../images/HR_re.jpg'),
    1998: require('../images/1998.png'),
    2002: require('../images/2002.png'),
    2013: require('../images/2013.png'),
    2016: require('../images/2016.png'),
    2020: require('../images/2020.png'),
    2024: require('../images/2024.png')
};

export default images;